FROM node:24-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
tini \
&& rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@10.33.0

WORKDIR /app

ENV PNPM_HOME=/tmp/.pnpm
ENV PATH="$PNPM_HOME:$PATH"
ENV PM2_HOME=/tmp/.pm2
ENV TMPDIR=/tmp

RUN mkdir -p /tmp/.pnpm /tmp/.pm2 && \
    chown -R node:node /tmp/.pnpm /tmp/.pm2

USER node

ENTRYPOINT ["tini", "--"]
